// Talker Machine — quiz question bank, keyed by unit number.
// Each entry is { q, choices: [...], correct: <index>, why: '...' }.
// Wrong answers are intentionally absurd / Duolingo-style so the correct
// answer is unmistakable and the quiz feels light. Explanations still teach.

export const QUIZ_BANK = {
  1: [ // What Is a Talker Machine?
    { q: 'A "talker machine" is most commonly known by what formal name?',
      choices: ['A pancake flipper', 'AAC device', 'A type of submarine', 'A flavor of yogurt'],
      correct: 1, why: 'AAC = Augmentative and Alternative Communication.' },
    { q: 'Which is NOT a type of AAC?',
      choices: ['Letter board (low-tech)', 'Picture book (low-tech)', 'A hammer', 'Tablet with Proloquo2Go (high-tech)'],
      correct: 2, why: 'AAC tools support communication — a hammer doesn\'t.' },
    { q: 'AAC stands for…',
      choices: ['Astronauts Always Cook', 'Augmentative and Alternative Communication', 'Annoying Avocado Cake', 'Antarctic Air Conditioner'],
      correct: 1, why: '"Augmentative" means it supplements speech; "Alternative" means it replaces speech entirely.' },
    { q: 'Who is the most famous user of a talker machine?',
      choices: ['SpongeBob SquarePants', 'Stephen Hawking', 'A pigeon named Frank', 'The Statue of Liberty'],
      correct: 1, why: 'Hawking used a DECtalk + cheek switch for 30+ years.' },
    { q: '"Low-tech" AAC includes:',
      choices: ['A potato', 'Paper letter boards & picture binders', 'A jet engine', 'Lasers from the moon'],
      correct: 1, why: 'Low-tech = no batteries, no electronics.' },
    { q: 'High-tech AAC usually means:',
      choices: ['Devices that speak', 'A loud sneeze', 'Throwing rocks at clouds', 'Whispering at a sandwich'],
      correct: 0, why: 'High-tech AAC = speech-generating devices (SGDs).' },
    { q: 'AAC is used by people who…',
      choices: ['Want to taste colors', 'Have difficulty using their voice', 'Need to grow taller', 'Hate Tuesdays'],
      correct: 1, why: 'Voice production or articulation difficulties are the core reason.' },
    { q: 'The opposite of "aided" AAC (like a board) is…',
      choices: ['Unaided AAC (gestures, sign, facial expression)', 'A toaster', 'A type of dance battle', 'Loud yelling at the wall'],
      correct: 0, why: 'Unaided AAC uses only the body — gestures, facial expression, sign language.' }
  ],
  2: [ // History — Letter Boards to Hawking's DECtalk
    { q: 'DECtalk was made by which company?',
      choices: ['SpaceX', 'Digital Equipment Corp.', 'A bakery in France', 'The Roman Empire'],
      correct: 1, why: 'DEC released DECtalk in 1984. It defined Hawking\'s voice.' },
    { q: 'Hawking\'s famous voice preset is called…',
      choices: ['Perfect Paul', 'Squeaky Steve', 'Big Bouncy Bob', 'Whispering Walrus'],
      correct: 0, why: '"Perfect Paul" is the deepest DECtalk male voice.' },
    { q: 'Before electronics, the simplest AAC was…',
      choices: ['A talking parrot', 'A letter / alphabet board', 'A trained dolphin', 'A magic wand'],
      correct: 1, why: 'Communication partners would read the letter the user pointed to.' },
    { q: 'Hawking lost most speech after which event?',
      choices: ['Eating a spicy taco', 'A 1985 tracheotomy', 'A llama race', 'A spelling bee'],
      correct: 1, why: 'Pneumonia → emergency tracheotomy in 1985 left him without voice.' },
    { q: 'What did Hawking use to drive his computer?',
      choices: ['A whistle and two hamsters', 'Eye-blink only', 'A cheek-muscle switch', 'Telepathy with his cat'],
      correct: 2, why: 'Late in life he used an infrared switch sensing his cheek twitch.' },
    { q: 'Hawking\'s later AAC software was developed by…',
      choices: ['A wizard named Greg', 'Intel (ACAT)', 'A choir of ducks', 'A baking show'],
      correct: 1, why: 'Intel\'s open-source ACAT (Assistive Context-Aware Toolkit).' },
    { q: 'First speech-generating devices appeared in the…',
      choices: ['Year 12,000 BC', '1960s–1970s', 'Tomorrow', 'The 1500s, made of cheese'],
      correct: 1, why: 'Dedicated SGDs began emerging alongside early personal computing.' },
    { q: 'A "communication book" is:',
      choices: ['A diary you whisper to', 'A printed binder of symbols/words for pointing', 'A book that argues with you', 'A novel set on Mars'],
      correct: 1, why: 'A low-tech aided AAC tool: pages of symbols organized by topic.' }
  ],
  3: [ // Types of AAC — Low-Tech to High-Tech
    { q: 'Which is low-tech AAC?',
      choices: ['A spaceship', 'Laminated picture board', 'A tornado simulator', 'A talking refrigerator'],
      correct: 1, why: 'Low-tech = no electronics or batteries.' },
    { q: 'A single-button voice recorder (e.g., BIGmack) is…',
      choices: ['A musical onion', 'Mid-tech', 'A bowling ball', 'A type of cloud'],
      correct: 1, why: 'Some battery & a chip but very limited — mid-tech.' },
    { q: 'High-tech AAC usually includes…',
      choices: ['Speech output and dynamic screens', 'A trained crow', 'Magic beans', 'A loud cucumber'],
      correct: 0, why: 'Dynamic display + speech engine = high-tech SGD.' },
    { q: 'Unaided AAC uses…',
      choices: ['A bicycle horn', 'A small volcano', 'Only the body (sign, gestures, gaze)', 'A radio antenna'],
      correct: 2, why: 'No external tool is involved.' },
    { q: 'A PODD book is which kind of AAC?',
      choices: ['A type of pasta', 'Low-tech / paper', 'A monster truck', 'A pop song'],
      correct: 1, why: 'PODD (Pragmatic Organisation Dynamic Display) is a paper communication book.' },
    { q: 'Which factor drives choice of AAC type?',
      choices: ['The color of the user\'s socks', 'User abilities & access needs', 'Phase of the moon', 'How many cats live nearby'],
      correct: 1, why: 'Match tool to motor / cognitive / visual abilities.' },
    { q: 'Switch-accessed AAC means…',
      choices: ['You flip a light switch and shout', 'A 1- or 2-button input scans through options', 'You yodel at a screen', 'You teach a goldfish to type'],
      correct: 1, why: 'Scanning + switch is common for users who can\'t touch a screen.' }
  ],
  4: [ // Symbol Systems — PCS, Bliss, SymbolStix
    { q: 'PCS stands for…',
      choices: ['Pizza Cheese Spaghetti', 'Picture Communication Symbols', 'Pretty Cool Skateboards', 'Painted Cat Sneakers'],
      correct: 1, why: 'PCS by Mayer-Johnson is the most widely used symbol set.' },
    { q: 'Blissymbols are…',
      choices: ['A flavor of ice cream', 'A meaning-based "ideographic" symbol language', 'A heavy metal band', 'A type of weather'],
      correct: 1, why: 'Charles Bliss designed them as a universal language of meaning.' },
    { q: 'SymbolStix symbols are characterized by…',
      choices: ['Photographs of dragons', 'Stick figures with bold action', 'Glowing alien hieroglyphs', 'Tap-dancing letters'],
      correct: 1, why: 'SymbolStix favors clear stick-figure visuals.' },
    { q: 'A "core" symbol is…',
      choices: ['A symbol made of fruit', 'A common, reusable word (I, want, more)', 'A symbol that does jumping jacks', 'A symbol that only appears on Fridays'],
      correct: 1, why: 'Core words are high-frequency words used across topics.' },
    { q: 'Symbols are typically arranged on a grid by…',
      choices: ['Which ones smell the best', 'Fitzgerald Key categories', 'Alphabetical screams', 'Throwing them in the air'],
      correct: 1, why: 'Fitzgerald: pronouns blue, verbs orange, etc.' },
    { q: 'Why use symbol AAC instead of text?',
      choices: ['Faster for non-readers and emergent communicators', 'Symbols are heavier', 'Words are illegal', 'Letters are scared of the dark'],
      correct: 0, why: 'Pre-literate or non-literate users can communicate via symbols.' }
  ],
  5: [ // Picture Boards & Communication Books
    { q: 'A picture board\'s grid usually shows…',
      choices: ['Random emoji confetti', 'Symbols + word label', 'Tiny portraits of you', 'Photos of cheese'],
      correct: 1, why: 'Symbol + text reinforces literacy as well as use.' },
    { q: 'A PODD book is organized…',
      choices: ['By weight in kilograms', 'Pragmatically — by conversation function', 'By zodiac sign', 'By how loud each page is'],
      correct: 1, why: 'PODD groups pages by intent: "I want", "I feel", "tell me".' },
    { q: 'Why include a "people" page?',
      choices: ['To list celebrities you have never met', 'To name family/friends/staff during conversation', 'To rank haircuts', 'To list strangers from the airport'],
      correct: 1, why: 'Naming people is a core conversational need.' },
    { q: 'Pointing at symbols is called…',
      choices: ['Direct selection', 'Aggressive jazz hands', 'Symbol surfing', 'Telepathic shouting'],
      correct: 0, why: 'Direct selection = user directly indicates the target.' },
    { q: 'A communication partner must…',
      choices: ['Shout louder than the user', 'Wait, watch, and acknowledge selections', 'Compete in a footrace', 'Read the user\'s mind perfectly'],
      correct: 1, why: 'Partner-assisted AAC requires patience and confirmation.' },
    { q: 'A "core board" displays…',
      choices: ['Bowling scores', 'High-frequency core words across pages', 'Weather forecasts only', 'A map of the user\'s neighborhood'],
      correct: 1, why: 'Core boards keep frequent words always accessible.' }
  ],
  6: [ // Speech-Generating Devices (SGDs)
    { q: 'An SGD is…',
      choices: ['A type of submarine', 'A dedicated speech-output device', 'A tiny rabbit', 'A type of sandwich'],
      correct: 1, why: 'Speech-Generating Device = produces spoken output.' },
    { q: 'A dedicated SGD differs from an iPad with an AAC app because…',
      choices: ['It only does communication, no apps', 'It can fly', 'It plays guitar', 'It cooks dinner'],
      correct: 0, why: 'Dedicated devices are locked to AAC use, easing funding & focus.' },
    { q: 'Most modern SGDs use…',
      choices: ['A choir of crickets', 'Synthetic text-to-speech (TTS)', 'A trained parrot inside', 'Bagpipes'],
      correct: 1, why: 'Dynamic TTS lets users speak any sentence they compose.' },
    { q: 'A common dedicated SGD brand is…',
      choices: ['Tobii Dynavox', 'McDonald\'s', 'Honda Civic', 'Lego Star Wars'],
      correct: 0, why: 'Tobii Dynavox is a leading SGD manufacturer.' },
    { q: 'Why use a dedicated SGD instead of a tablet?',
      choices: ['Robust hardware, locked to AAC, often funded by insurance', 'They glow in the dark', 'They make pancakes', 'They argue with toasters'],
      correct: 0, why: 'Funding programs often pay for dedicated devices, not consumer tablets.' },
    { q: 'A "dynamic display" SGD means…',
      choices: ['Pages change based on selection', 'The screen does cartwheels', 'It plays disco music', 'It changes color with mood'],
      correct: 0, why: 'Selecting "food" opens a food page; selecting "feelings" opens a feelings page.' }
  ],
  7: [ // Eye-Tracking & Switch Access
    { q: 'Eye-tracking AAC uses cameras to detect…',
      choices: ['Where the user is looking on screen', 'Eyebrow length', 'How much you\'ve slept', 'The weather'],
      correct: 0, why: 'Gaze coordinates select cells on the AAC grid.' },
    { q: 'A "dwell" in eye-gaze means…',
      choices: ['Holding gaze on a target for a set time = selection', 'Falling asleep at the screen', 'Crying with one eye', 'Sneezing on demand'],
      correct: 0, why: 'Dwell duration is how the device confirms a "click" by eye.' },
    { q: 'A "switch" in AAC is…',
      choices: ['A traffic light', 'A single button (or 2) the user can hit reliably', 'A type of pasta', 'A surfboard'],
      correct: 1, why: 'Big buttons, sip-and-puff, cheek switches, foot switches, etc.' },
    { q: 'Scanning AAC works by…',
      choices: ['Highlighting choices in sequence; user hits switch when target appears', 'Reading a barcode on your forehead', 'Counting freckles', 'Smelling the device for clues'],
      correct: 0, why: 'Step / row-column scanning gives switch users access to large grids.' },
    { q: 'Tobii makes…',
      choices: ['Eye-tracking devices', 'Toothpicks', 'Boats', 'Magic potions'],
      correct: 0, why: 'Tobii is a leading eye-tracking company.' },
    { q: 'A sip-and-puff switch detects…',
      choices: ['Cucumber slices', 'Breath in & breath out as 2 inputs', 'Whether you brushed your teeth', 'Whistle volume'],
      correct: 1, why: 'Users with limited mobility can drive AAC via breath.' }
  ],
  8: [ // Modern AAC Apps — Proloquo2Go, TouchChat, LAMP
    { q: 'Proloquo2Go runs on which platform?',
      choices: ['iOS / iPadOS', 'A Game Boy', 'A bicycle', 'The kitchen sink'],
      correct: 0, why: 'AssistiveWare\'s Proloquo2Go is iOS-only.' },
    { q: 'TouchChat is made by…',
      choices: ['Saltillo', 'The Tooth Fairy', 'A rock band', 'Ancient Egypt'],
      correct: 0, why: 'Saltillo (part of PRC-Saltillo).' },
    { q: 'LAMP stands for…',
      choices: ['Language Acquisition through Motor Planning', 'Large Annoying Magic Pumpkin', 'Lasers Aimed Mostly Politely', 'Lemonade and Marshmallow Party'],
      correct: 0, why: 'LAMP uses consistent motor pathways for each word.' },
    { q: 'LAMP Words for Life is designed for…',
      choices: ['Children with autism, esp. for motor-based learning', 'Goldfish', 'Time travelers', 'Roller coasters'],
      correct: 0, why: 'Motor planning gives word-locations consistency.' },
    { q: 'A "vocabulary page set" in TouchChat is called…',
      choices: ['WordPower, MultiChat', 'PizzaWorld', 'SnoreBuddy', 'CrocoBlast'],
      correct: 0, why: 'WordPower and MultiChat are common vocab sets.' },
    { q: 'Why use a dedicated AAC app vs typing into Notes?',
      choices: ['Faster speech production, symbol support, sentence-building grids', 'Notes is allergic to wifi', 'It scares the cat less', 'Notes only speaks Latin'],
      correct: 0, why: 'AAC apps are built for speed, scaffolding, and access methods.' }
  ],
  9: [ // Vocabulary — Core vs Fringe
    { q: 'Core words are…',
      choices: ['Common, reusable across topics', 'Made entirely of jelly', 'Words shaped like donuts', 'Words that only work on Tuesdays'],
      correct: 0, why: '"I", "want", "more", "go" work in many contexts.' },
    { q: 'Fringe words are…',
      choices: ['Topic-specific (e.g., "pizza", "spider")', 'Words that wear capes', 'Words living in the wilderness', 'Words from Mars'],
      correct: 0, why: 'Fringe vocabulary is more specific and changes by topic.' },
    { q: 'About how much of daily speech is core?',
      choices: ['~80%', '0.000001%', '4 million percent', 'Only on weekends'],
      correct: 0, why: '~80% of what we say is the same ~200 core words.' },
    { q: 'A balanced AAC vocab should…',
      choices: ['Have both core (always accessible) and rich fringe pages', 'Have only the word "banana"', 'Use only sneezes', 'Be entirely in Klingon'],
      correct: 0, why: 'Core for power; fringe for richness and specificity.' },
    { q: 'An example of CORE is…',
      choices: ['"want"', '"chimichanga"', '"saxophone"', '"hippopotamus"'],
      correct: 0, why: '"want" is one of the most-used English words.' },
    { q: 'An example of FRINGE is…',
      choices: ['"pizza"', '"the"', '"I"', '"want"'],
      correct: 0, why: 'Pizza is topic-specific — fringe.' }
  ],
  10: [ // Modeling AAC — Aided Language Stimulation
    { q: 'Aided Language Stimulation (ALgS) means a partner…',
      choices: ['Models target words on the AAC device while speaking', 'Hides the device under a rug', 'Reads tarot cards', 'Bakes a cake for the user'],
      correct: 0, why: 'Partners model use of the device in real situations.' },
    { q: 'Modeling AAC works because…',
      choices: ['Learners need to see AAC used naturally', 'Cats demand it', 'It rhymes with "doodling"', 'The government requires it on weekends'],
      correct: 0, why: 'You can\'t learn a language without seeing it used.' },
    { q: 'How much modeling does research suggest?',
      choices: ['Dozens of models per day, all environments', 'Only during full moons', 'Once every leap year', 'Only while wearing a top hat'],
      correct: 0, why: 'Heavy modeling accelerates AAC acquisition.' },
    { q: '"Wait time" with AAC users means…',
      choices: ['Pause 5–45 seconds for response', 'Wait for the next bus', 'Wait until your hair grows', 'Wait until the Olympics'],
      correct: 0, why: 'AAC users need processing & motor time to respond.' },
    { q: 'Modeling should be…',
      choices: ['Natural — embedded in real conversation', 'A loud opera performance', 'Silent and confusing', 'Performed in interpretive dance'],
      correct: 0, why: 'Pair the spoken word with the symbol selection in context.' }
  ],
  11: [ // Voices & Text-to-Speech Engines
    { q: 'TTS stands for…',
      choices: ['Text-to-Speech', 'Two Talking Squirrels', 'Tiny Tap Shoes', 'Thunderous Tortilla Symphony'],
      correct: 0, why: 'Software that converts written text into spoken audio.' },
    { q: 'DECtalk produced Hawking\'s voice using…',
      choices: ['Formant synthesis', 'A rubber duck and a kazoo', 'Three trained parrots', 'A church bell'],
      correct: 0, why: 'Formant synthesis builds vowels & consonants from filtered tones.' },
    { q: 'A modern neural TTS engine (e.g., WaveNet) is…',
      choices: ['Trained on human speech recordings to sound natural', 'A whale that learned English', 'A choir of cheese graters', 'Powered by hamster wheels'],
      correct: 0, why: 'Neural networks produce near-human prosody.' },
    { q: 'AAC users often keep their old robotic voice because…',
      choices: ['It became their identity', 'It scares mosquitoes', 'It\'s a legal requirement on Wednesdays', 'It plays better music'],
      correct: 0, why: 'Hawking refused to switch to a "better" voice — it was him.' },
    { q: '"Voice banking" lets a user…',
      choices: ['Record their own voice for future TTS', 'Deposit their voice into a checking account', 'Trade voices with a celebrity', 'Loan their voice to ghosts'],
      correct: 0, why: 'Pre-recording sentences/phonemes preserves the user\'s voice before speech loss.' },
    { q: 'iOS\'s built-in TTS voices are called…',
      choices: ['Siri / system voices', 'Karen and Steve from accounting', 'The Boris Boys', 'Whispering Wendy'],
      correct: 0, why: 'AAC apps can use system TTS voices on iOS.' }
  ],
  12: [ // AAC for Autism
    { q: 'About what % of autistic people are minimally verbal?',
      choices: ['~30%', '1,000,000%', 'Three (just three)', 'Only on national holidays'],
      correct: 0, why: 'Roughly 25–30% remain minimally or non-verbal into adulthood.' },
    { q: 'AAC for autistic users often emphasizes…',
      choices: ['Core vocabulary, motor planning, modeling', 'Telepathy', 'Loud trumpet noises', 'Disco lessons'],
      correct: 0, why: 'LAMP-style apps use consistent motor patterns for words.' },
    { q: 'A common myth is that AAC will…',
      choices: ['Stop speech development (FALSE — it supports it)', 'Turn people into cats', 'Cause lightning storms', 'Make houses float'],
      correct: 0, why: 'Evidence shows AAC supports, not hinders, speech acquisition.' },
    { q: 'PECS stands for…',
      choices: ['Picture Exchange Communication System', 'Powerful Edible Cheesy Sandwich', 'Penguins Eating Crunchy Snacks', 'Pickled Elephants Casually Sneezing'],
      correct: 0, why: 'A common starter AAC method for autistic learners.' },
    { q: 'A presumption-of-competence approach means…',
      choices: ['Assume the user can learn and offer rich language', 'Assume they\'re a robot', 'Assume they live underwater', 'Assume they\'re actually a wizard'],
      correct: 0, why: 'Don\'t gate language access behind cognitive testing.' }
  ],
  13: [ // AAC for ALS, Cerebral Palsy & Stroke
    { q: 'ALS users may need AAC because…',
      choices: ['Progressive loss of speech & motor control', 'Their tongue went on vacation', 'They turned into a squirrel', 'Loud thunderclap allergy'],
      correct: 0, why: 'ALS attacks motor neurons, eventually affecting speech.' },
    { q: 'A common AAC access for late-stage ALS is…',
      choices: ['Eye tracking', 'Tap dancing', 'Whispering at a houseplant', 'Sending smoke signals'],
      correct: 0, why: 'Eye gaze is one of the last reliable inputs.' },
    { q: 'Aphasia (post-stroke) often impairs…',
      choices: ['Word retrieval and language processing', 'Pizza appetite only', 'Ability to wink', 'Knowledge of the alphabet song in Latin'],
      correct: 0, why: 'Aphasia is a language disorder — AAC supports retrieval.' },
    { q: 'Cerebral palsy affects mainly…',
      choices: ['Motor control (including for speech)', 'Hat size', 'Favorite color', 'Knowledge of dinosaurs'],
      correct: 0, why: 'Damage to developing brain affects movement; speech production may be affected.' },
    { q: 'Voice banking is most relevant for…',
      choices: ['ALS users before they lose speech', 'People who own banks', 'Voice actors only', 'People named Bank Bankerton'],
      correct: 0, why: 'Recording before progressive loss preserves the personal voice.' }
  ],
  14: [ // Funding, Insurance & Schools
    { q: 'In the US, SGDs may be covered by…',
      choices: ['Medicare/Medicaid + private insurance', 'A coupon from a cereal box', 'A polite letter to the moon', 'A choir of accountants'],
      correct: 0, why: 'SGDs are durable medical equipment; many plans cover them.' },
    { q: 'An IEP includes AAC when…',
      choices: ['A student needs it to access curriculum', 'The student requests it in Pig Latin', 'It\'s the principal\'s birthday', 'A pigeon delivers the form'],
      correct: 0, why: 'IDEA requires assistive tech in the student\'s IEP if needed for FAPE.' },
    { q: 'A school SLP\'s role with AAC includes…',
      choices: ['Assessment, training, programming, modeling', 'Driving the school bus', 'Coaching the chess team', 'Running the pizza counter'],
      correct: 0, why: 'Speech-Language Pathologists lead AAC services in schools.' },
    { q: 'A "dedicated" SGD is often funded because…',
      choices: ['It\'s locked to AAC use → meets medical-necessity criteria', 'It\'s a tiny luxury yacht', 'It\'s actually free pizza', 'It\'s glittery'],
      correct: 0, why: 'Lockdown helps qualify under insurance.' },
    { q: 'Trial period for AAC is important to…',
      choices: ['Match the right tool to the user before purchase', 'Test if the device floats', 'Train the device to fetch', 'Teach the device to whistle'],
      correct: 0, why: 'Trials prevent expensive mismatches.' }
  ],
  15: [ // Talker Machine Mastery
    { q: 'The fundamental purpose of AAC is to…',
      choices: ['Give the user a voice', 'Replace breakfast', 'Annoy birds', 'Improve cake recipes'],
      correct: 0, why: 'AAC is about communication access and autonomy.' },
    { q: 'Best AAC outcomes come from…',
      choices: ['Heavy modeling + appropriate tool + trained partners + presumption of competence', 'A single magic crystal', 'A lucky rabbit foot', 'Yelling at the device'],
      correct: 0, why: 'No single magic bullet — it\'s an ecosystem.' },
    { q: 'A talker machine that doesn\'t get used probably…',
      choices: ['Was a poor fit for the user / context', 'Hates Mondays', 'Is on vacation', 'Has a grudge against humans'],
      correct: 0, why: 'Abandonment usually means the wrong tool, not the wrong user.' },
    { q: 'Core vocabulary is roughly _ of daily speech.',
      choices: ['80%', '4 grams', '17 hours', 'A medium pizza'],
      correct: 0, why: '~80% of what we say is the same small set of core words.' },
    { q: 'The most important thing about AAC users is…',
      choices: ['They\'re people with something to say', 'Their favorite snack', 'Their height in centimeters', 'How many beads they own'],
      correct: 0, why: 'Assume competence and provide rich communication access.' }
  ]
};
