#!/usr/bin/env python3
"""Unit 39 — Geometric (Clifford) Algebra (lessons 571-585)."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from gen_vectors import render_unit

LESSONS = [
    {"title": "From Cross Product to Geometric Product",
     "body_html": r"""
<p>The cross product is awkward: it only works in 3D, and it conflates "an oriented area" with "a vector perpendicular to it." <strong>Geometric algebra</strong> (Clifford algebra) generalizes by introducing the <strong>geometric product</strong>:</p>
<div class="math-block">$$\vec{a}\vec{b} = \vec{a}\cdot\vec{b} + \vec{a}\wedge\vec{b}$$</div>
<p>It's the sum of a scalar (the dot product) and a <strong>bivector</strong> (the wedge — an oriented plane element). One product encoding both pieces of geometric information.</p>""",
     "exercises": [
         {"type": "true-false", "question": "Geometric product = dot + wedge.", "correctAnswer": True},
         {"type": "multiple-choice", "question": "Cross product works in:", "options": ["any dimension", "only 3D", "only 2D", "any odd dim"], "correctIndex": 1},
         {"type": "fill-blank", "question": "The wedge piece is a ___.", "answer": "bivector"},
         {"type": "true-false", "question": "Clifford algebra works in any dimension.", "correctAnswer": True},
         {"type": "true-false", "question": "Geometric product is commutative for general vectors.", "correctAnswer": False}]},
    {"title": "The Clifford Algebra Cl(n)",
     "body_html": r"""
<p>The Clifford algebra \(\text{Cl}(n)\) over \(\mathbb{R}^n\) is generated by basis vectors \(\vec{e}_1, \ldots, \vec{e}_n\) satisfying</p>
<div class="math-block">$$\vec{e}_i^2 = 1, \quad \vec{e}_i \vec{e}_j = -\vec{e}_j \vec{e}_i \ (i \neq j)$$</div>
<p>So vectors square to scalars, and distinct basis vectors anti-commute. The algebra contains scalars, vectors, bivectors, ..., up to the top-grade <strong>pseudoscalar</strong>. Total dimension: \(2^n\).</p>
<p>For Cl(1, 3) (Minkowski signature), \(\vec{e}_0^2 = 1\) but \(\vec{e}_i^2 = -1\) for \(i = 1, 2, 3\). This is the <strong>spacetime algebra</strong>.</p>""",
     "exercises": [
         {"type": "fill-blank", "question": r"\(\text{Cl}(n)\) has dimension \(2^?\). Fill: ___.", "answer": "n"},
         {"type": "multiple-choice", "question": r"In Cl(n), \(\vec{e}_i \vec{e}_j + \vec{e}_j \vec{e}_i =\)", "options": [r"\(\vec{e}_i\)", r"\(2\delta_{ij}\)", "0", "1"], "correctIndex": 1},
         {"type": "true-false", "question": "Distinct basis vectors anticommute in Clifford algebra.", "correctAnswer": True},
         {"type": "fill-blank", "question": "The spacetime algebra is Cl(___,3). Fill: ___.", "answer": "1"},
         {"type": "true-false", "question": r"In Cl(n), \(\vec{e}_i^2 = 1\) (Euclidean signature).", "correctAnswer": True}]},
    {"title": "Multivectors",
     "body_html": r"""
<p>A <strong>multivector</strong> is a sum of pieces of different grades:</p>
<div class="math-block">$$M = \underbrace{\alpha}_{\text{scalar}} + \underbrace{\vec{v}}_{\text{vector}} + \underbrace{B}_{\text{bivector}} + \underbrace{T}_{\text{trivector}} + \cdots$$</div>
<p>The grade of an element is the lowest dim it spans. The whole algebra is the direct sum of grade subspaces:</p>
<div class="math-block">$$\text{Cl}(n) = \bigoplus_{k=0}^n \Lambda^k(\mathbb{R}^n)$$</div>
<p>Grade-\(k\) part has dimension \(\binom{n}{k}\). Total: \(\sum_k \binom{n}{k} = 2^n\).</p>""",
     "exercises": [
         {"type": "true-false", "question": "Multivectors are sums of pieces of different grades.", "correctAnswer": True},
         {"type": "fill-blank", "question": r"Dim of grade-\(k\) part of Cl(n): \(\binom{n}{?}\). Fill: ___.", "answer": "k"},
         {"type": "multiple-choice", "question": "Grade of a scalar:", "options": ["0", "1", "2", "n"], "correctIndex": 0},
         {"type": "true-false", "question": "Total dim of Cl(n) = 2^n.", "correctAnswer": True},
         {"type": "fill-blank", "question": "Bivectors have grade ___.", "answer": "2"}]},
    {"title": "Bivectors as Oriented Areas",
     "body_html": r"""
<p>A <strong>bivector</strong> represents an oriented plane element. For two vectors \(\vec{a}, \vec{b}\):</p>
<div class="math-block">$$\vec{a}\wedge\vec{b} = -\vec{b}\wedge\vec{a}$$</div>
<p>magnitude is the area of the parallelogram, and orientation is from \(\vec{a}\) to \(\vec{b}\).</p>
<p>Unlike the cross product, bivectors live <strong>in the plane they describe</strong>, not perpendicular to it. This makes them the right object in any dimension — and removes the right-hand-rule ambiguity.</p>""",
     "exercises": [
         {"type": "true-false", "question": "Bivectors live in the plane, not perpendicular to it.", "correctAnswer": True},
         {"type": "fill-blank", "question": r"\(\vec{a}\wedge\vec{b} = -\vec{b}\wedge\) ___.", "answer": "a"},
         {"type": "multiple-choice", "question": "Magnitude of a wedge of two vectors:", "options": ["dot product", "area of parallelogram", "trace", "sum"], "correctIndex": 1},
         {"type": "true-false", "question": "Cross product and wedge product agree in 3D up to a Hodge dual.", "correctAnswer": True},
         {"type": "true-false", "question": "Bivectors only make sense in 3D.", "correctAnswer": False}]},
    {"title": "Trivectors & Volumes",
     "body_html": r"""
<p>A <strong>trivector</strong> represents an oriented volume element. \(\vec{a}\wedge\vec{b}\wedge\vec{c}\): magnitude is the volume of the parallelepiped, sign is the orientation.</p>
<p>In 3D, the trivector subspace is 1-dim: every trivector is a multiple of \(\vec{e}_1\wedge\vec{e}_2\wedge\vec{e}_3 = I\) (the unit pseudoscalar).</p>
<p>The pseudoscalar \(I\) plays a role analogous to the imaginary unit in 3D — it squares to \(-1\) (with appropriate signature). Multiplication by \(I\) implements duality: \(\vec{a} I\) is the bivector "perpendicular to \(\vec{a}\)."</p>""",
     "exercises": [
         {"type": "true-false", "question": "Trivectors represent oriented volumes.", "correctAnswer": True},
         {"type": "fill-blank", "question": r"In 3D, the trivector space is ___-dimensional.", "answer": "1"},
         {"type": "multiple-choice", "question": r"\(I = \vec{e}_1 \vec{e}_2 \vec{e}_3\) is called the:", "options": ["pseudoscalar", "metric", "biscalar", "trivector unit"], "correctIndex": 0},
         {"type": "true-false", "question": r"\(I^2 = -1\) in 3D.", "correctAnswer": True},
         {"type": "true-false", "question": "Multiplication by I implements duality.", "correctAnswer": True}]},
    {"title": "Rotations via Geometric Product",
     "body_html": r"""
<p>Reflections compose into rotations. A <strong>rotor</strong> \(R = \cos(\theta/2) - B\sin(\theta/2)\) (where \(B\) is a unit bivector in the plane of rotation) implements rotation by \(\theta\):</p>
<div class="math-block">$$\vec{v}' = R\vec{v}R^{-1}$$</div>
<p>This works in any dimension. For 3D, rotors are equivalent to unit quaternions. The "double cover" by spin groups (rotor by \(\theta/2\)) explains why \(720°\) rather than \(360°\) brings a spinor back to itself.</p>""",
     "exercises": [
         {"type": "fill-blank", "question": r"Rotor: \(R = \cos(\theta/2) - B \sin(\) ___\()\).", "answer": "theta/2"},
         {"type": "multiple-choice", "question": r"3D rotors correspond to:", "options": ["complex numbers", "unit quaternions", "matrices only", "tensors"], "correctIndex": 1},
         {"type": "true-false", "question": "Rotors work in any dimension.", "correctAnswer": True},
         {"type": "fill-blank", "question": r"Rotation: \(\vec{v}' = R\vec{v} R^?\). Fill: ___.", "answer": "-1"},
         {"type": "true-false", "question": "A spinor returns to itself after a 360° rotation.", "correctAnswer": False}]},
    {"title": "Reflections in GA",
     "body_html": r"""
<p>Reflection of a vector \(\vec{v}\) across a plane normal to unit vector \(\hat{n}\):</p>
<div class="math-block">$$\vec{v}' = -\hat{n}\vec{v}\hat{n}$$</div>
<p>Cleaner than the matrix \(I - 2\hat{n}\hat{n}^T\). The composition of two reflections gives a rotation — that's how rotors arise.</p>
<p>Reflections also generalize beyond vectors: the same formula reflects multivectors of any grade.</p>""",
     "exercises": [
         {"type": "true-false", "question": "Two reflections compose to a rotation.", "correctAnswer": True},
         {"type": "multiple-choice", "question": r"Reflection in GA: \(\vec{v}' =\)", "options": [r"\(\hat{n}\vec{v}\hat{n}\)", r"\(-\hat{n}\vec{v}\hat{n}\)", r"\(\vec{v} + \hat{n}\)", r"\(-\vec{v}\)"], "correctIndex": 1},
         {"type": "fill-blank", "question": "Rotors arise from products of ___.", "answer": "reflections"},
         {"type": "true-false", "question": "GA reflection works for higher-grade multivectors too.", "correctAnswer": True},
         {"type": "true-false", "question": "GA reflection requires matrices.", "correctAnswer": False}]},
    {"title": "Spinors",
     "body_html": r"""
<p><strong>Spinors</strong> are elements of the spin group (a double cover of the rotation group). In GA they appear as rotors. They satisfy the unusual property that a \(360°\) rotation gives a sign flip; \(720°\) is needed to return to the identity.</p>
<p>Spinors describe particles like electrons, quarks — the fundamental fermions of the standard model. The Dirac equation lives naturally in spacetime algebra, formulated in terms of spinors.</p>""",
     "exercises": [
         {"type": "true-false", "question": "Spinors require 720° to return to identity.", "correctAnswer": True},
         {"type": "multiple-choice", "question": "Electrons are described by:", "options": ["scalars", "vectors", "spinors", "tensors"], "correctIndex": 2},
         {"type": "fill-blank", "question": "Dirac equation involves ___.", "answer": "spinors"},
         {"type": "true-false", "question": "Spin group is a double cover of rotation group.", "correctAnswer": True},
         {"type": "true-false", "question": "Fermions have integer spin.", "correctAnswer": False}]},
    {"title": "GA in 2D = Complex Numbers",
     "body_html": r"""
<p>The 2D Clifford algebra Cl(2) has a unit pseudoscalar \(I = \vec{e}_1\vec{e}_2\) with \(I^2 = -1\). The even subalgebra (scalars + bivectors) is exactly the complex numbers \(\mathbb{C}\):</p>
<div class="math-block">$$z = a + bI \leftrightarrow a + bi$$</div>
<p>Multiplication by \(e^{I\theta} = \cos\theta + I\sin\theta\) rotates 2D vectors by \(\theta\). This is exactly the geometric meaning of complex multiplication.</p>""",
     "exercises": [
         {"type": "true-false", "question": "Even subalgebra of Cl(2) is the complex numbers.", "correctAnswer": True},
         {"type": "fill-blank", "question": r"In Cl(2), \(I^2 =\) ___.", "answer": "-1"},
         {"type": "multiple-choice", "question": r"\(e^{I\theta}\) acts on a 2D vector as:", "options": ["scaling by θ", "rotation by θ", "reflection", "no change"], "correctIndex": 1},
         {"type": "true-false", "question": "Cl(2) recovers complex multiplication's rotation structure.", "correctAnswer": True},
         {"type": "true-false", "question": "Cl(0) is just the integers.", "correctAnswer": False}]},
    {"title": "GA in 3D",
     "body_html": r"""
<p>Cl(3) has dimension \(2^3 = 8\): scalars, 3 basis vectors, 3 basis bivectors, 1 pseudoscalar. The bivectors square to \(-1\), making the even subalgebra (scalars + bivectors) isomorphic to the <strong>quaternions</strong>.</p>
<p>So 3D GA includes quaternions for free, plus vectors, plus a clean way to combine them. Rotors in Cl(3) are unit elements of this even subalgebra — exactly unit quaternions.</p>""",
     "exercises": [
         {"type": "true-false", "question": "Even subalgebra of Cl(3) is the quaternions.", "correctAnswer": True},
         {"type": "fill-blank", "question": r"Cl(3) has dimension ___.", "answer": "8"},
         {"type": "multiple-choice", "question": "Bivectors in Cl(3) square to:", "options": ["+1", "-1", "0", "complex numbers"], "correctIndex": 1},
         {"type": "true-false", "question": "Unit rotors in Cl(3) correspond to unit quaternions.", "correctAnswer": True},
         {"type": "fill-blank", "question": r"Number of basis bivectors in 3D: ___.", "answer": "3"}]},
    {"title": "Spacetime Algebra Cl(1,3)",
     "body_html": r"""
<p>Cl(1, 3) is the algebra of <strong>spacetime</strong>. \(\vec{e}_0^2 = 1\) (time), \(\vec{e}_i^2 = -1\) for \(i = 1, 2, 3\) (space). Lorentz transformations are realized as \(\vec{v}' = R\vec{v}R^{-1}\) for spacetime rotors \(R\).</p>
<p>The electromagnetic field becomes a single bivector \(F\) with \(\vec{E}\) and \(\vec{B}\) parts. Maxwell's equations collapse to one equation: \(\nabla F = J\) (where \(\nabla\) is the spacetime gradient operator). One equation, one bivector — the cleanest formulation of EM.</p>""",
     "exercises": [
         {"type": "true-false", "question": "Cl(1,3) has Minkowski signature.", "correctAnswer": True},
         {"type": "multiple-choice", "question": "EM field in spacetime algebra is a:", "options": ["scalar", "vector", "bivector", "trivector"], "correctIndex": 2},
         {"type": "fill-blank", "question": r"Maxwell's equations in GA: \(\nabla F = \) ___.", "answer": "J"},
         {"type": "true-false", "question": "Lorentz transformations are spacetime rotors.", "correctAnswer": True},
         {"type": "true-false", "question": "GA reduces Maxwell's 4 equations to 1.", "correctAnswer": True}]},
    {"title": "Maxwell in GA",
     "body_html": r"""
<p>In spacetime algebra:</p>
<div class="math-block">$$F = \vec{E} + I_3\vec{B}, \quad \nabla F = J$$</div>
<p>where \(\nabla = \vec{e}_0\partial_t - \vec{e}_1\partial_x - \vec{e}_2\partial_y - \vec{e}_3\partial_z\) is the spacetime vector derivative, \(I_3 = \vec{e}_1\vec{e}_2\vec{e}_3\), and \(J\) packages charge density and current.</p>
<p>The single equation \(\nabla F = J\) splits into Maxwell's four when you decompose by grades. Same physics; far cleaner notation.</p>""",
     "exercises": [
         {"type": "fill-blank", "question": r"\(F = \vec{E} + I_3\) ___.", "answer": "B"},
         {"type": "multiple-choice", "question": r"Single equation Maxwell in GA:", "options": [r"\(\nabla F = J\)", r"\(F = J\)", r"\(d F = 0\)", r"\(\nabla \cdot F = J\)"], "correctIndex": 0},
         {"type": "true-false", "question": "GA reduces Maxwell to a single bivector equation.", "correctAnswer": True},
         {"type": "true-false", "question": "Decomposing by grades recovers all four classical Maxwell equations.", "correctAnswer": True},
         {"type": "fill-blank", "question": r"\(\nabla\) is the spacetime ___ operator.", "answer": "gradient"}]},
    {"title": "Why GA Matters",
     "body_html": r"""
<p>Reasons GA is gaining traction:</p>
<ul>
<li><strong>Unification:</strong> dot products, cross products, complex numbers, quaternions, spinors, tensors — all aspects of one algebra.</li>
<li><strong>Coordinate-free formulas</strong> that work in any dimension.</li>
<li><strong>No more ambiguous right-hand rule</strong> — orientations are baked into multivectors.</li>
<li><strong>Numerical robustness</strong> for graphics, robotics, computer vision (rotor quaternions are well-conditioned).</li>
<li><strong>Mathematical elegance</strong> in physics: rewrites of Maxwell, Dirac, GR all become more transparent.</li>
</ul>""",
     "exercises": [
         {"type": "true-false", "question": "GA unifies several algebraic structures.", "correctAnswer": True},
         {"type": "multiple-choice", "question": "GA is used in:", "options": ["graphics and robotics", "physics formulations", "any dimension", "all of these"], "correctIndex": 3},
         {"type": "fill-blank", "question": "GA removes the ambiguity of the ___-hand rule.", "answer": "right"},
         {"type": "true-false", "question": "GA is used widely in major engineering software.", "correctAnswer": True},
         {"type": "true-false", "question": "GA is purely theoretical.", "correctAnswer": False}]},
    {"title": "Practice: Multivector Multiplication",
     "body_html": r"""
<p>Examples in Cl(3):</p>
<ol>
<li>\(\vec{e}_1 \vec{e}_1 = 1\). \(\vec{e}_1 \vec{e}_2 = -\vec{e}_2 \vec{e}_1\) (bivector).</li>
<li>\(\vec{e}_1 (\vec{e}_2\vec{e}_3) = \vec{e}_1\vec{e}_2\vec{e}_3 = I\) (the pseudoscalar).</li>
<li>\((\vec{e}_1 + \vec{e}_2)(\vec{e}_1 + \vec{e}_2) = \vec{e}_1^2 + 2\vec{e}_1\vec{e}_2 + \vec{e}_2^2\)? No — \(\vec{e}_1\vec{e}_2 + \vec{e}_2\vec{e}_1 = 0\), so the cross-terms cancel: result is \(2\). The square of a vector is its norm squared.</li>
<li>For two vectors \(\vec{a}, \vec{b}\): \(\vec{a}\vec{b} + \vec{b}\vec{a} = 2(\vec{a}\cdot\vec{b})\), \(\vec{a}\vec{b} - \vec{b}\vec{a} = 2(\vec{a}\wedge\vec{b})\).</li>
</ol>""",
     "exercises": [
         {"type": "fill-blank", "question": r"\(\vec{e}_1^2 =\) ___.", "answer": "1"},
         {"type": "multiple-choice", "question": r"\(\vec{a}\vec{b} + \vec{b}\vec{a} =\)", "options": [r"\(\vec{a}\cdot\vec{b}\)", r"\(2\vec{a}\cdot\vec{b}\)", r"\(0\)", r"\(\vec{a}\wedge\vec{b}\)"], "correctIndex": 1},
         {"type": "true-false", "question": r"\(\vec{e}_1\vec{e}_2 + \vec{e}_2\vec{e}_1 = 0\).", "correctAnswer": True},
         {"type": "fill-blank", "question": r"\((\vec{e}_1 + \vec{e}_2)^2 =\) ___ in Cl(3).", "answer": "2"},
         {"type": "true-false", "question": r"Vector squared is its squared magnitude.", "correctAnswer": True}]},
    {"title": "GA Checkpoint",
     "body_html": r"""
<p>Recap of Unit 39:</p>
<ul>
<li>Geometric product: \(\vec{a}\vec{b} = \vec{a}\cdot\vec{b} + \vec{a}\wedge\vec{b}\).</li>
<li>Multivectors: scalars + vectors + bivectors + trivectors + ...</li>
<li>Bivectors are oriented plane elements; trivectors oriented volumes.</li>
<li>Reflections: \(\vec{v}' = -\hat n \vec{v} \hat n\). Two reflections = rotation (rotor).</li>
<li>Rotors generalize complex numbers (in 2D) and quaternions (in 3D).</li>
<li>Spacetime algebra Cl(1,3) realizes Lorentz transformations as rotors.</li>
<li>Maxwell's equations reduce to \(\nabla F = J\) in spacetime algebra.</li>
</ul>""",
     "exercises": [
         {"type": "true-false", "question": "GA generalizes the cross product to any dimension.", "correctAnswer": True},
         {"type": "multiple-choice", "question": r"\(\vec{a}\vec{b} = \vec{a}\cdot\vec{b} +\)", "options": [r"\(\vec{a}\wedge\vec{b}\)", r"\(\vec{a}\times\vec{b}\)", "0", r"\(\vec{b}\)"], "correctIndex": 0},
         {"type": "fill-blank", "question": "Bivectors represent oriented ___.", "answer": "areas"},
         {"type": "true-false", "question": "Cl(3)'s even subalgebra is the quaternions.", "correctAnswer": True},
         {"type": "true-false", "question": "GA simplifies Maxwell's equations to one equation.", "correctAnswer": True},
         {"type": "fill-blank", "question": "Spacetime algebra signature: Cl(1, ___).", "answer": "3"},
         {"type": "true-false", "question": "Spinors return to themselves under 360° rotation.", "correctAnswer": False}]},
]

if __name__ == "__main__":
    render_unit(39, "Geometric (Clifford) Algebra", 571, LESSONS)
